# Generated by Django 4.2.10 on 2025-10-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0004_alter_nail_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nail',
            name='service_type',
            field=models.CharField(choices=[('Biab', 'Biab'), ('Biab Refill', 'Biab Refill'), ('Gel Polish', 'Gel Polish'), ('Gel Polish Refill', 'Gel Polish Refill')], max_length=100),
        ),
    ]
