# Generated by Django 4.2.10 on 2025-10-21 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupiedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupiedDates', to='Nail_App_Bookin.nail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_dates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OccupiedDate',
        ),
    ]
