# Generated by Django 4.2.10 on 2025-10-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0002_occupieddates_delete_occupieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nail',
            name='design',
            field=models.CharField(choices=[('Plain', 'plain'), ('Tier 1 Design', 'small design'), ('Tier 2 Design', 'medium design'), ('Tier 3 Design', 'hard design')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nailimage',
            name='image',
            field=models.ImageField(upload_to='nail_images/'),
        ),
    ]
