# Generated by Django 4.2.10 on 2025-10-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0003_alter_nail_design_alter_nailimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nail',
            name='design',
            field=models.CharField(choices=[('Plain', 'Plain'), ('Tier 1 Design', 'Tier 1 Design'), ('Tier 2 Design', 'Tier 2 Design'), ('Tier 3 Design', 'Tier 3 Design')], max_length=100),
        ),
    ]
