# Generated by Django 4.2.10 on 2025-11-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0007_alter_nailimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nailimage',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
