# Generated by Django 4.2.10 on 2025-11-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0008_alter_nailimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nailimage',
            name='image',
            field=models.ImageField(upload_to='nail_images/'),
        ),
    ]
