# Generated by Django 5.2.6 on 2026-01-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0009_alter_nailimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupieddates',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='occupieddates',
            unique_together={('nail', 'date', 'time')},
        ),
    ]
