# Generated by Django 5.2.6 on 2026-02-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0010_add_time_to_occupieddates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occupieddates',
            unique_together=set(),
        ),
    ]
