# Generated by Django 5.2.6 on 2026-02-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0011_alter_occupieddates_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occupieddates',
            unique_together={('nail', 'date', 'time')},
        ),
    ]
