# Generated by Django 5.2.6 on 2026-04-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0012_alter_occupieddates_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupieddates',
            name='time',
            field=models.TimeField(default=12),
        ),
    ]
