# Generated by Django 5.2.6 on 2026-04-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nail_App_Bookin', '0013_alter_occupieddates_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupieddates',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
    ]
